
// ============================================================
// WS5 \u2014 Datenanalyse Verwaltung (VetMedAI, 11.06.2026)
// Generiert aus build_content.py \u2014 nicht von Hand editieren.
// ============================================================

function getWs5Content() {
  return [
    { type: "title", title: "Datenanalyse\nin der Verwaltung", subtitle: "Von Prompt Engineering zu Context Engineering", meta: "Workshop 5 \u00b7 11. Juni 2026 \u00b7 Online\nVetMedAI \u00b7 KI-Kompetenzaufbau Veterin\u00e4rmedizinische Universit\u00e4t Wien" },

    { type: "content", title: "Claude Fable 5", body: "Anthropic ver\u00f6ffentlicht am 9. Juni 2026 **Claude Fable 5**, das erste \u00f6ffentliche Modell der **Mythos-Klasse**.\n\n\u2022 Eigene Leistungsstufe \u00fcber den bisherigen Spitzenmodellen (*Opus*)\n\u2022 Stand der Technik auf nahezu allen *Benchmarks*, darunter *Software Engineering* und Wissensarbeit\n\u2022 Arbeitet **l\u00e4nger autonom** an komplexen Aufgaben als jedes fr\u00fchere Modell\n\nDrei Jahre nach dem *GPT-4*-Beispiel von 2023 (Teil 1) setzt sich die Entwicklung unvermindert fort.", source: "Anthropic (2026). Claude Fable 5 and Claude Mythos 5. anthropic.com/news/claude-fable-5-mythos-5 \u00b7 Video: \"Claude Fable is Live...and its WILD!\", youtube.com/watch?v=KwQXyyVl2cM", notes: "Anthropic hat am 9. Juni 2026 Claude Fable 5 veroeffentlicht, das erste oeffentlich zugaengliche Modell der Mythos-Klasse. Fable 5 uebertrifft die Opus-Modelle bei laengeren, komplexeren Aufgaben und arbeitet laenger autonom als alle frueheren Claude-Modelle. Anthropic berichtet Bestwerte unter anderem in Software Engineering, Wissensarbeit, Bildverstehen und wissenschaftlicher Recherche. Das Kontextfenster umfasst eine Million Token, der Preis liegt bei 10 Dollar pro Million Eingabe-Token und 50 Dollar pro Million Ausgabe-Token. Fuer den Workshop zaehlt der Befund, dass die Modellentwicklung seit dem GPT-4-Beispiel von 2023 nicht stagniert." },

    { type: "content", title: "Fable 5 und Mythos 5: gestufte Freigabe", body: "**Mythos 5** (volles Modell) erh\u00e4lt nur ein kleiner Kreis von Cyberverteidigern und Infrastrukturbetreibern (*Project Glasswing*, mit der US-Regierung).\n\n**Fable 5** (\u00f6ffentlich) nutzt dieselbe Technologie mit **Klassifikatoren**: Anfragen zu *Cybersecurity*, Bio/Chemie oder Modell-*Destillation* \u00fcbernimmt automatisch das schw\u00e4chere Modell *Opus 4.8*.\n\nDie Schutzschicht liegt beim Anbieter, die fachliche Pr\u00fcfung der Ergebnisse beim Nutzer: **Das Werkzeug rechnet, der Mensch verantwortet.**\n\nDie Live-Demo in Teil 3 l\u00e4uft auf *Fable 5*.", source: "Anthropic (2026). Claude Fable 5 and Claude Mythos 5. anthropic.com/news/claude-fable-5-mythos-5", notes: "Die Mythos-Modelle fanden Anfang 2026 Sicherheitsluecken auf einem Niveau, das die Cybersecurity-Branche alarmierte. Das volle Modell Mythos 5 erhaelt deshalb nur ein kleiner Kreis von Cyberverteidigern und Infrastrukturbetreibern im Rahmen von Project Glasswing in Kooperation mit der US-Regierung. Das oeffentliche Fable 5 basiert auf derselben Technologie. Klassifikatoren erkennen Anfragen zu Cybersecurity, Biologie und Chemie sowie Modell-Destillation und uebergeben sie automatisch an das schwaechere Modell Opus 4.8. Die Schutzschicht liegt damit beim Anbieter, die fachliche Pruefung der Ergebnisse bleibt Aufgabe der Nutzerinnen und Nutzer. Die Live-Demo in Teil 3 laeuft auf Fable 5." },

    { type: "learning", title: "Lernziele", body: "1. Tabellarische **Verwaltungsdaten** (*Excel*, *CSV*) mit *LLM*-Unterst\u00fctzung auswerten und visualisieren\n\n2. **Code-Ausf\u00fchrung** f\u00fcr zuverl\u00e4ssige Berechnungen nutzen und von reiner Textantwort unterscheiden\n\n3. Ergebnisse **kritisch verifizieren**: Datenqualit\u00e4t, Quersummen, Fachwissen (*Critical Expert in the Loop*)\n\n4. **Grenzen** und datenschutzkonformen Einsatz (*Academic AI*) einordnen" },

    { type: "section", title: "Teil 1", subtitle: "Was ist Datenanalyse mit LLMs? Eine kurze Geschichte" },

    { type: "content", title: "2023: Das Ausgangsexperiment", body: "Eine *Excel*-Tabelle mit ausgewerteten Frageb\u00f6gen. Die Frage: Wer w\u00fcrde die eigenen kognitiven F\u00e4higkeiten verbessern, und mit welchen Methoden?\n\n\u2022 Saubere Variablen, gute Datengrundlage\n\u2022 Werkzeug: *GPT-4* mit *Advanced Data Analysis*\n\u2022 Ergebnis in rund eineinhalb Tagen\n\nDamals eher zuf\u00e4llig schon **richtig** verwendet: erst die Daten lesen, dann analysieren, dann visualisieren.", source: "Daten: Grinschgl et al., OSF-Projekt, Erhebung 2022.", notes: "Das Beispiel stammt aus einem realen Projekt zu kognitivem Enhancement. Die Teilnehmenden beantworteten Frageboegen dazu, ob sie aktive oder passive Methoden zur Steigerung ihrer kognitiven Faehigkeiten akzeptieren. Entscheidend war die saubere Datengrundlage mit klar definierten Variablen. GPT-4 mit Advanced Data Analysis fuehrte echten Python-Code aus und lieferte die Auswertung in etwa eineinhalb Tagen." },

    { type: "handson", title: "Der Prompt von 2023", body: "Bausteine, die man damals brauchte:\n\n\u2022 **Persona Modelling**\n\u2022 **Kontext** und **Aufgabe** in Schritten\n\u2022 *Chain-of-Thought*: Schritt f\u00fcr Schritt denken\n\u2022 *Emotional Prompting*: \"important to my career\"\n\nHeute ist das meiste davon **nicht mehr n\u00f6tig**.", prompt: "You are an expert in psychology\nand data visualization. Here is a\ndataset ...\n\n* Read the csv very carefully\n* Define user stories based on the\n  data and research questions\n* Implement the data visualizations\n\nTake a deep breath and work on this\nstep-by-step. This is very important\nto my career!", notes: "Der Originalprompt kombinierte Persona Modelling, Kontext, Arbeitsschritte und zwei Techniken, die heute Zeitgeschichte sind. Chain-of-Thought wurde damals in den OpenAI-Discord-Channels aufgeschnappt, Emotional Prompting sollte das Modell zu mehr Sorgfalt bewegen. Aktuelle Modelle koennen das von sich aus, der Aufwand entfaellt." },

    { type: "content", title: "Was sich ver\u00e4ndert hat", body: "***Prompt Engineering* verliert, *Context Engineering* gewinnt.**\n\n\u2022 2023: Die Kunst lag im **Bedienen** des Modells\n\u2022 Heute: Die Arbeit liegt im pr\u00e4zisen **Bereitstellen** von Aufgabe, Prozess und Daten\n\nDie Verbesserung in drei Jahren war **kategorisch**, nicht graduell. Am st\u00e4rksten dort, wo eine gute Datengrundlage vorliegt.", notes: "Der Kompetenzschwerpunkt hat sich verschoben. Frueher ging es darum, das Modell mit Tricks zu bedienen. Heute liegt die Arbeit darin, Aufgabe, Prozess und Daten praezise bereitzustellen. Diese Verschiebung ist die zentrale Botschaft des ersten Teils." },

    { type: "handson", title: "Heute: ein Satz gen\u00fcgt", body: "Derselbe Datensatz, heute in *Claude Code*:\n\n1. Daten und Codebook selbst herunterladen lassen\n2. Passende statistische Verfahren eigenst\u00e4ndig w\u00e4hlen\n3. Visualisierungen erzeugen\n4. Forschungsfragen beantworten\n\nStatt *Persona* und Tricks: eine **pr\u00e4zise Aufgabe** mit guter Datengrundlage.", prompt: "Lies Daten und Codebook unter <URL>\nund analysiere sie sorgf\u00e4ltig.\n\nForschungsfrage: Korreliert\nIntelligenz mit der Akzeptanz von\nEnhancement-Methoden?\n\nW\u00e4hle eigenst\u00e4ndig die passenden\nVerfahren und Visualisierungen,\nbegr\u00fcnde deine Wahl, dokumentiere\ndie Schritte.", notes: "Derselbe Anwendungsfall wie 2023, aber heute genuegt eine praezise Aufgabe. Claude Code laedt die Daten selbst herunter, liest das Codebook, waehlt die statistischen Verfahren und beantwortet die Forschungsfragen weitgehend autonom. Der Mensch nennt nur noch Frage und Datengrundlage." },

    { type: "content", title: "*Claude Code*: was man dabei sieht", body: "\u2022 **Terminal und *Tool Use***: das Modell l\u00e4dt die Daten selbst herunter und f\u00fchrt Code aus\n\u2022 **Permissions**: vor jeder eingreifenden Aktion fragt es nach\n\u2022 ***Read***: es liest das Codebook-PDF direkt, nichts wird abgetippt\n\u2022 **Sichtbares *Reasoning***: man sieht, was es vorhat, und kann eingreifen\n\nDas sichtbare Denken ist der **Feedback-Kanal** f\u00fcr den Menschen.", notes: "Vier Funktionen von Claude Code werden am Enhancement-Lauf sichtbar. Das Modell baut sich selbst einen Befehl, um die Daten herunterzuladen, fragt vor der Ausfuehrung um Erlaubnis, liest das Codebook-PDF direkt und zeigt sein Reasoning. Das sichtbare Denken erlaubt es, einzugreifen bevor eine falsche Richtung eingeschlagen wird." },

    { type: "content_with_image", title: "Das Ergebnis: ein \u00dcberblick", body: "Die Korrelationsmatrix zeigt:\n\n\u2022 Tats\u00e4chliche und selbsteingesch\u00e4tzte Intelligenz h\u00e4ngen moderat zusammen (*r* = 0,47)\n\u2022 Intelligenz und Akzeptanz von Enhancement: durchgehend **schwach**\n\u2022 Aktive Methoden *r* = 0,14, passive praktisch null\n\nN = 257.", placeholder: "fig3_heatmap.png\nKorrelationsmatrix der fokalen Variablen", source: "Eigene Analyse, Claude Code (2026)." },

    { type: "content_with_image", title: "Die Falle: signifikant, aber nicht haltbar", body: "Aktive Methode \u00d7 tats\u00e4chliche Intelligenz:\n\n\u2022 rohes *p* = **0,027**, sieht signifikant aus\n\u2022 nach **Holm-Korrektur**: *p* = 0,109, **n.s.**\n\nBei vier Tests muss man f\u00fcr multiples Testen korrigieren. Danach h\u00e4lt **keiner** der vier Zusammenh\u00e4nge.\n\n2023 w\u00e4re man hier in die Falle gelaufen: ein Effekt, den es nicht gibt.", placeholder: "fig1_scatter_grid.png\nVier Streudiagramme mit r, CI, p, Holm", source: "Holm (1979). Scand. J. of Statistics.", notes: "Das ist der didaktische Kern des ersten Teils. Das rohe p von 0,027 wirkt signifikant. Nach der Holm-Korrektur fuer multiples Testen steht 0,109 und der Zusammenhang haelt nicht mehr. Wer nur das rohe p liest, berichtet einen Effekt, den es nicht gibt. Das Modell hat hier korrekt korrigiert, aber verlassen darf man sich darauf nicht." },

    { type: "content", title: "*Critical Expert in the Loop*", body: "Das Modell hat hier richtig korrigiert. **Verlassen** darf man sich darauf nicht.\n\nDie menschliche Rolle verschiebt sich von **Bedienung** zu **Validierung**:\n\u2022 Wissen, *dass* man bei vier Tests korrigieren muss\n\u2022 Das Ergebnis im Output **gegenpr\u00fcfen**\n\u2022 Fachlich verantworten, was berichtet wird\n\nKonstant von 2023 bis heute: die **fachliche Validierung**.", notes: "Die Verantwortung bleibt beim Menschen. Das Modell schlaegt vor und rechnet, die Fachperson entscheidet, ob das Ergebnis traegt. Diese Rolle bleibt von 2023 bis heute konstant, waehrend sich die Werkzeuge stark veraendert haben. Damit leitet der erste Teil zum Verwaltungsfall ueber." },

    { type: "section", title: "Teil 2", subtitle: "Datenanalyse im Verwaltungsalltag" },

    { type: "content", title: "Der Anwendungsfall: Wissensbilanz", body: "Die **Wissensbilanz** braucht Personalkennzahlen je Organisationseinheit, dazu die Geschlechterverteilung.\n\n\u2022 Bisher: manuell in *Excel* zusammengetragen\n\u2022 Jetzt: im Dialog mit dem Modell, mit Kontrolle\n\nAnschluss an **Use Case 1** (Wissensbilanz-Dashboard), den Sie bereits kennen.", notes: "Der Hauptteil arbeitet mit einem echten Verwaltungsfall. Die Wissensbilanz der Universitaet braucht Personalkennzahlen je Organisationseinheit und die Geschlechterverteilung. Bisher wurde das manuell in Excel zusammengetragen. Der Fall knuepft an Use Case 1 des Projekts an, das Wissensbilanz-Dashboard." },

    { type: "content", title: "Das Werkzeug: niederschwellig", body: "*ChatGPT* oder *Claude* mit **Datei-Upload** und *Code-Interpreter*. Kein Terminal, kein Code-Schreiben.\n\n\u2022 *Excel* hochladen, Frage stellen, rechnen lassen, visualisieren\n\n**Datenschutz:** Echte Personaldaten geh\u00f6ren nicht in \u00f6ffentliche Tools. Daf\u00fcr die *Academic AI* der VetMed nutzen. Heute arbeiten wir mit **synthetischen** Daten.", notes: "Anders als die Claude-Code-Hinfuehrung laeuft der Hauptteil ueber ein niederschwelliges Werkzeug. Eine Excel-Datei wird in ChatGPT oder Claude hochgeladen, der Code-Interpreter rechnet. Fuer echte Personaldaten ist die Academic AI der VetMed der datenschutzkonforme Weg. Die heutige Demo nutzt bewusst synthetische Daten." },

    { type: "handson", title: "Schritt 1: \u00dcberblick verschaffen", body: "1. *Excel*-Datei hochladen (Blatt \"Personal\", 150 Zeilen)\n2. Das Modell den Aufbau beschreiben lassen\n3. Nach **Datenqualit\u00e4tsproblemen** fragen\n\nEin gutes Modell meldet schon hier: gemischte Zahlenformate, fehlende Werte.", prompt: "Ich habe eine Excel-Datei mit\nPersonaldaten hochgeladen (Blatt\n\"Personal\"). Verschaff dir einen\n\u00dcberblick: Zeilen, Spalten, und\nwelche Datenqualit\u00e4tsprobleme\nfallen dir auf? Noch keine\nAuswertung." },

    { type: "content_with_image", title: "Schritt 2: Z\u00e4hlen, und die Falle", body: "Frage: Personen je Organisationseinheit.\n\nDas Modell listet **zwei** Kleintierkliniken getrennt: \"Universit\u00e4tsklinik f\u00fcr Kleintiere\" (12) und \"Univ.-Klinik f. Kleintiere\" (8).\n\n**Dieselbe Klinik, zwei Schreibweisen.** Korrekt zusammengef\u00fchrt: **20**.\n\nDie Zahl sieht sauber aus und ist trotzdem falsch.", placeholder: "admin_falle_schreibvariante.png\nBalken: 8 + 12 gespalten vs. 20 korrekt", notes: "Genau dieselbe Klasse Fehler wie die Holm-Geschichte, nur im Verwaltungsfeld. Das Modell zaehlt zwei Schreibweisen derselben Klinik als getrennte Einheiten. Die korrekte Zahl ist 20, nicht 12. Die Fachperson erkennt, dass zwei Labels eine Einheit sind, das Modell nicht zuverlaessig." },

    { type: "content", title: "Schritt 3: Rechnen lassen, nicht raten", body: "Die Summe der Vollzeit\u00e4quivalente (VZ\u00c4):\n\n\u2022 **Aus dem Bauch gesch\u00e4tzt**: das Modell nennt irgendeine plausible Zahl, unzuverl\u00e4ssig\n\u2022 **Mit *Code-Interpreter***: exakt **110,00**, aber nur, wenn die Komma-Werte (\"0,75\") sauber bereinigt werden\n\nReine Textantwort bei Zahlen ist riskant. **Code-Ausf\u00fchrung erzwingen** und die Aufbereitung pr\u00fcfen.", notes: "Der Kontrast zeigt, warum Code-Ausfuehrung zaehlt. Eine reine Sprachmodell-Schaetzung von Zahlen ist unzuverlaessig. Der Code-Interpreter liefert exakt 110,00 Vollzeitaequivalente, aber nur wenn die als Text gespeicherten Komma-Werte vorher bereinigt werden. Verlaesslichkeit haengt an Code-Ausfuehrung und sauberer Aufbereitung zugleich." },

    { type: "content_with_image", title: "Schritt 4: Visualisieren", body: "Geschlechterverteilung, gesamt und je Funktionsgruppe:\n\n\u2022 gesamt 69 w, 80 m, 1 d, **Frauenanteil 46 %**\n\u2022 je Funktionsgruppe direkt als Balkendiagramm\n\n**Verifikation:** Quersumme pr\u00fcfen. 69 + 80 + 1 = 150 = Zeilenzahl. Stimmt sie nicht, hat das Modell stillschweigend Zeilen verloren.", placeholder: "admin_geschlecht.png\nGeschlecht gesamt und je Funktionsgruppe" },

    { type: "content", title: "Schritt 5: F\u00fcr den Bericht aufbereiten", body: "Eine Tabelle je Organisationseinheit mit Kopfzahl und VZ\u00c4, dazu drei S\u00e4tze Flie\u00dftext f\u00fcr die Entscheidungsvorlage.\n\n**Verifikation:**\n\u2022 Gesamt-Kopfzahl muss 150 sein, Gesamt-VZ\u00c4 110,00\n\u2022 Der Text darf nur behaupten, was die Tabelle zeigt\n\u2022 Kein \"deutlicher Anstieg\" ohne Zeitreihe", notes: "Am Ende steht ein berichtsfertiges Ergebnis. Eine Tabelle je Organisationseinheit mit Kopfzahl und Vollzeitaequivalenten plus ein kurzer Fliesstext fuer die Entscheidungsvorlage. Die Verifikation prueft, ob die Gesamtsummen stimmen und ob der Text nur behauptet, was die Tabelle belegt." },

    { type: "content", title: "Die Grenzen kennen", body: "\u2022 **Rechenfehler ohne Code**: Textantworten zu Zahlen sind unzuverl\u00e4ssig\n\u2022 **Halluzination bei Zahlen**: plausibel, aber falsch\n\u2022 **Dom\u00e4nenfehler**: zwei Schreibweisen als eine Einheit erkennt das Modell nicht zuverl\u00e4ssig\n\u2022 **Gr\u00f6\u00dfenlimits**: sehr gro\u00dfe Dateien werden gek\u00fcrzt oder gesampelt\n\u2022 **Datenschutz**: keine echten Personaldaten in \u00f6ffentliche Tools" },

    { type: "content", title: "Verifikations-Checkliste Verwaltung", body: "1. Stimmt die **Quersumme** mit der Zeilenzahl \u00fcberein?\n2. Wurde mit **Code** gerechnet, nicht gesch\u00e4tzt?\n3. Sind Kategorien **konsolidiert** (Schreibvarianten, Tippfehler, Einheiten)?\n4. Behauptet der **Text** nur, was die Tabelle zeigt?\n5. Bei echten Daten: **datenschutzkonformes** Werkzeug?", notes: "Die Checkliste fasst die Verifikationsschritte zusammen, die im Verwaltungsalltag tragen. Quersumme gegen Zeilenzahl, Rechnen mit Code statt Schaetzung, konsolidierte Kategorien, Deckung von Text und Tabelle, und bei echten Daten ein datenschutzkonformes Werkzeug." },

    { type: "section", title: "Teil 3", subtitle: "Live-Demo Claude Code und Einordnung" },

    { type: "content", title: "Live: vom Bericht zum Dashboard", body: "Der dritte Teil wechselt zu **echten Daten**: den \u00f6ffentlichen **Wissensbilanzen** der Vetmeduni 2012 bis 2025 (vierzehn PDFs).\n\n\u2022 Referenzprojekt: PDFs, daraus gepr\u00fcfte Kennzahlen, daraus ein **Dashboard**\n\u2022 Methode **Promptotyping**: erst Wissen in Dokumente (*DATA.md*, *SPECIFICATION.md*), dann Code\n\u2022 \u00d6ffentliche Daten, daher ist ein *Cloud*-Agent wie *Claude Code* hier unbedenklich\n\nLive arbeiten wir mit der fertigen Kennzahlen-Datei; die fragile PDF-Extraktion ist vorbereitet.", source: "Wissensbilanzen der Veterin\u00e4rmedizinischen Universit\u00e4t Wien (vetmeduni.ac.at, Berichte) \u00b7 Repo: vetmed-datenanalyse", notes: "Der dritte Teil arbeitet mit echten oeffentlichen Daten. Universitaeten muessen ihre Wissensbilanz jaehrlich veroeffentlichen, die Kennzahlen folgen der Wissensbilanz-Verordnung. Das Referenzprojekt vetmed-datenanalyse extrahiert aus den vierzehn PDFs der Jahrgaenge 2012 bis 2025 die Personal- und Drittmittelkennzahlen und baut daraus ein Dashboard. Die Methode ist Promptotyping, also Wissen in Dokumenten vor Code. Weil alle Daten oeffentlich sind, ist der Einsatz eines Cloud-Agenten unbedenklich. Fuer interne oder personenbezogene Daten gilt das nicht, dort bleibt die Academic AI der Weg. Die PDF-Extraktion ist vorbereitet, weil sie auf echten Quellen fragil ist. Die Live-Demo arbeitet mit der fertigen Kennzahlen-Datei." },

    { type: "handson", title: "Der Arbeitsauftrag", body: "Worauf Sie live achten k\u00f6nnen:\n\n1. **Kontext zuerst**: das Modell liest *DATA.md*, bevor es rechnet\n2. **Permissions**: vor jeder Ausf\u00fchrung kommt die Nachfrage\n3. **Tests als Gate**: der **Datenvertrag** muss gr\u00fcn bleiben\n4. Ergebnis: das **Dashboard** im Browser", prompt: "Lies knowledge/DATA.md und\nknowledge/SPECIFICATION.md.\nArbeite mit den Kennzahlen in\ndata/kennzahlen/.\nPr\u00fcfe zuerst den Datenvertrag\n(python -m pytest -q).\nBaue dann das Dashboard neu und\nfasse die wichtigsten Befunde zu\nPersonal, Frauenanteil und\nDrittmitteln zusammen.", notes: "Der Auftrag wird live in Claude Code ausgefuehrt. Das Modell liest zuerst die Wissensdokumente DATA.md und SPECIFICATION.md, das ist der Kern von Promptotyping. Vor jeder Skript-Ausfuehrung kommt die Permission-Nachfrage. Der Datenvertrag in tests/test_datenvertrag.py prueft zwanzig Bedingungen, darunter Quersummen, Frauenanteile und verankerte Sollwerte aus den PDFs. Erst wenn die Tests gruen sind, wird das Dashboard gebaut und im Browser geoeffnet." },

    { type: "content_with_image", title: "Befund: Frauenanteil 2012 bis 2025", body: "\u2022 Wissenschaftliches Personal: Frauenanteil von **59 auf 66 %**\n\u2022 Professor:innen (ab 2021 berichtet): von **32 auf 53 %**, von 12 auf 25 Personen\n\u2022 Kleine Grundgesamtheit bei Professuren: einzelne Berufungen bewegen die Kurve stark\n\nLesehinweis: Die Werte sind **Kopfzahlen**, nicht *Vollzeit\u00e4quivalente*.", placeholder: "wb_frauenanteil.png\nFrauenanteil wiss. Personal und Professor:innen", source: "Wissensbilanzen Vetmeduni 2012\u20132025, Kennzahl 1.A.1; eigene Aufbereitung (vetmed-datenanalyse).", notes: "Die Abbildung zeigt den Frauenanteil nach Kopfzahl aus vierzehn Jahrgaengen. Im wissenschaftlichen Personal stieg der Anteil von 59,3 auf 66,4 Prozent. Bei den Professuren, die erst ab 2021 getrennt berichtet werden, stieg er von 31,6 auf 53,2 Prozent, in absoluten Zahlen von 12 auf 25 Professorinnen. Bei kleinen Grundgesamtheiten bewegen einzelne Berufungen die Kurve stark, das gehoert zur Interpretation dazu. Die Werte beziehen sich auf Kopfzahlen, nicht auf Vollzeitaequivalente." },

    { type: "content_with_image", title: "Befund: Personal und Drittmittel", body: "\u2022 Wissenschaftliches Personal: von 648 K\u00f6pfen (2012) zum H\u00f6chststand 2019, zuletzt 777\n\u2022 Drittmittelerl\u00f6se (F&E) schwanken deutlich: Spitze **21,7 Mio Euro** (2019), danach R\u00fcckgang und Erholung\n\u2022 Einzelne Gro\u00dfprojekte pr\u00e4gen die Jahressumme; die Schwankung selbst ist kein Alarmsignal", placeholder: "wb_personal_drittmittel.png\nPersonalstand und Drittmittelerl\u00f6se", source: "Wissensbilanzen Vetmeduni, Kennzahlen 1.A.1 und 1.C.1; eigene Aufbereitung (vetmed-datenanalyse).", notes: "Das wissenschaftliche Personal waechst von 648 Koepfen im Jahr 2012 auf einen Hoechststand um 2019 und liegt zuletzt bei 777. Das allgemeine Personal verlaeuft parallel auf niedrigerem Niveau. Die Drittmittelerloese aus Forschung und Entwicklung schwanken zwischen rund 10 und 21,7 Millionen Euro, das Spitzenjahr ist 2019. Einzelne Grossprojekte praegen die Jahressumme, deshalb ist die Schwankung selbst kein Alarmsignal. Beide Reihen stammen aus denselben oeffentlichen Berichten." },

    { type: "content_with_image", title: "Das Dashboard", body: "Eine einzige *HTML*-Datei, offline lauff\u00e4hig:\n\n\u2022 Kennzahlen-Karten mit Vorjahresvergleich\n\u2022 Diagramme zu Frauenanteil, Personalstand, Drittmitteln\n\u2022 Umschalter Kopfzahl/*VZ\u00c4*, Jahresfilter, *PNG*- und *CSV*-Export\n\nGebaut im Dialog mit *Claude Code*, gesichert durch den **Datenvertrag**.", placeholder: "wb_dashboard.png\nDashboard mit Kennzahlen-Karten und Frauenanteil", source: "vetmed-datenanalyse, dashboard/index.html.", notes: "Das Dashboard ist eine einzelne HTML-Datei ohne externe Abhaengigkeiten und laeuft offline per Doppelklick. Es zeigt Kennzahlen-Karten mit Vorjahresvergleich, Diagramme zu Frauenanteil, Personalstand und Drittmitteln, einen Umschalter zwischen Kopfzahl und Vollzeitaequivalenten, Jahresfilter sowie Export als PNG und CSV. Gebaut wurde es im Dialog mit Claude Code, die Datenbasis sichert der Datenvertrag mit zwanzig Pruefungen." },

    { type: "content", title: "Verifikation: der Datenvertrag", body: "Bei echten Daten pr\u00fcfen **Tests** statt bekannter Sollwerte:\n\n\u2022 **Konsistenz**: Frauen plus M\u00e4nner ergibt Gesamt, keine L\u00fccken, Frauenanteil korrekt berechnet\n\u2022 **Quellbindung**: verankerte Werte aus den PDFs (*Golden Values*), \u00dcberlappung benachbarter Jahrg\u00e4nge\n\nKonsistenz allein sichert keine Korrektheit gegen die Quelle. Die Anker setzt der Mensch: *Critical Expert in the Loop*.\n\n**Mehr Autonomie hei\u00dft mehr Verifikation, nicht weniger.** Vertiefung: *VetMed Winter School*.", notes: "Bei echten Daten gibt es keine vorab bekannten Sollwerte wie beim synthetischen Datensatz in Teil 2. An ihre Stelle tritt der Datenvertrag mit zwanzig Pruefungen auf zwei Ebenen. Die Konsistenzebene prueft, dass Frauen plus Maenner Gesamt ergibt, dass keine Jahrgaenge fehlen und dass der Frauenanteil korrekt berechnet ist. Die Quellbindungsebene verankert einzelne Werte direkt aus den PDFs und prueft die Ueberlappung benachbarter Jahrgaenge. Konsistenz allein sichert keine Korrektheit gegen die Quelle, erst beide Ebenen zusammen. Die verankerten Werte hat der Mensch aus den Quellen gesetzt. Je autonomer das Werkzeug arbeitet, desto wichtiger wird diese Pruefung. Die VetMed Winter School vertieft den Arbeitsmodus." },

    { type: "content", title: "Welches Werkzeug wann?", body: "\u2022 **Schnell und niederschwellig**: *ChatGPT* oder *Claude* mit Datei-Upload, f\u00fcr einmalige Auswertungen\n\u2022 **Datenschutzkonform**: *Academic AI* der VetMed, f\u00fcr echte Personal- und Verwaltungsdaten\n\u2022 **M\u00e4chtig und wiederholbar**: *Claude Code*, f\u00fcr wiederkehrende oder komplexe Auswertungen\n\nDie Frage ist nicht \"welches Tool\", sondern \"welche Aufgabe\".", notes: "Die drei Werkzeuge decken unterschiedliche Beduerfnisse ab. Datei-Upload fuer schnelle Einzelauswertungen, Academic AI fuer echte Verwaltungsdaten, Claude Code fuer wiederkehrende oder komplexe Aufgaben. Der Ausgangspunkt ist immer die Aufgabe, nicht das Werkzeug." },

    { type: "discussion", question: "Welche wiederkehrende Auswertung aus Ihrem Arbeitsalltag w\u00fcrden Sie als Erstes mit einem *LLM* ausprobieren, und welche Datenqualit\u00e4tsfalle erwarten Sie dabei?" },

    { type: "content", title: "Zusammenfassung", body: "Die durchgehende Linie:\n\n\u2022 2023: Kompetenz war **Prompt Engineering** (Persona, *Chain-of-Thought*, Tricks)\n\u2022 Heute: Kompetenz ist **Context Engineering** (Aufgabe, Prozess, Daten pr\u00e4zise bereitstellen)\n\u2022 Konstant: die **fachliche Validierung**\n\nDas Werkzeug rechnet. **Der Mensch verantwortet.**", notes: "Die Zusammenfassung spannt den Bogen ueber beide Teile. Frueher lag die Kompetenz im Prompt Engineering, heute im Context Engineering. Konstant bleibt die fachliche Validierung. Das Werkzeug rechnet, der Mensch verantwortet das Ergebnis." }
  ];
}
