
// ============================================================
// WS5 Delta \u2014 Fable-5-Opener + Teil-3-Live-Demo (10.06.2026)
// Generiert aus build_content.py \u2014 nicht von Hand editieren.
// Fuer generateAppend(): haengt hinten an, danach manuell
// einsortieren (Opener nach Folie 1, Live-Demo nach Section Teil 3).
// ============================================================

function getWs5DeltaContent() {
  return [
    { type: "content", title: "Claude Fable 5", body: "Anthropic ver\u00f6ffentlicht am 9. Juni 2026 **Claude Fable 5**, das erste \u00f6ffentliche Modell der **Mythos-Klasse**.\n\n\u2022 Eigene Leistungsstufe \u00fcber den bisherigen Spitzenmodellen (*Opus*)\n\u2022 Stand der Technik auf nahezu allen *Benchmarks*, darunter *Software Engineering* und Wissensarbeit\n\u2022 Arbeitet **l\u00e4nger autonom** an komplexen Aufgaben als jedes fr\u00fchere Modell\n\nDrei Jahre nach dem *GPT-4*-Beispiel von 2023 (Teil 1) setzt sich die Entwicklung unvermindert fort.", source: "Anthropic (2026). Claude Fable 5 and Claude Mythos 5. anthropic.com/news/claude-fable-5-mythos-5 \u00b7 Video: \"Claude Fable is Live...and its WILD!\", youtube.com/watch?v=KwQXyyVl2cM", notes: "Anthropic hat am 9. Juni 2026 Claude Fable 5 veroeffentlicht, das erste oeffentlich zugaengliche Modell der Mythos-Klasse. Fable 5 uebertrifft die Opus-Modelle bei laengeren, komplexeren Aufgaben und arbeitet laenger autonom als alle frueheren Claude-Modelle. Anthropic berichtet Bestwerte unter anderem in Software Engineering, Wissensarbeit, Bildverstehen und wissenschaftlicher Recherche. Das Kontextfenster umfasst eine Million Token, der Preis liegt bei 10 Dollar pro Million Eingabe-Token und 50 Dollar pro Million Ausgabe-Token. Fuer den Workshop zaehlt der Befund, dass die Modellentwicklung seit dem GPT-4-Beispiel von 2023 nicht stagniert." },

    { type: "content", title: "Fable 5 und Mythos 5: gestufte Freigabe", body: "**Mythos 5** (volles Modell) erh\u00e4lt nur ein kleiner Kreis von Cyberverteidigern und Infrastrukturbetreibern (*Project Glasswing*, mit der US-Regierung).\n\n**Fable 5** (\u00f6ffentlich) nutzt dieselbe Technologie mit **Klassifikatoren**: Anfragen zu *Cybersecurity*, Bio/Chemie oder Modell-*Destillation* \u00fcbernimmt automatisch das schw\u00e4chere Modell *Opus 4.8*.\n\nDie Schutzschicht liegt beim Anbieter, die fachliche Pr\u00fcfung der Ergebnisse beim Nutzer: **Das Werkzeug rechnet, der Mensch verantwortet.**\n\nDie Live-Demo in Teil 3 l\u00e4uft auf *Fable 5*.", source: "Anthropic (2026). Claude Fable 5 and Claude Mythos 5. anthropic.com/news/claude-fable-5-mythos-5", notes: "Die Mythos-Modelle fanden Anfang 2026 Sicherheitsluecken auf einem Niveau, das die Cybersecurity-Branche alarmierte. Das volle Modell Mythos 5 erhaelt deshalb nur ein kleiner Kreis von Cyberverteidigern und Infrastrukturbetreibern im Rahmen von Project Glasswing in Kooperation mit der US-Regierung. Das oeffentliche Fable 5 basiert auf derselben Technologie. Klassifikatoren erkennen Anfragen zu Cybersecurity, Biologie und Chemie sowie Modell-Destillation und uebergeben sie automatisch an das schwaechere Modell Opus 4.8. Die Schutzschicht liegt damit beim Anbieter, die fachliche Pruefung der Ergebnisse bleibt Aufgabe der Nutzerinnen und Nutzer. Die Live-Demo in Teil 3 laeuft auf Fable 5." },

    { type: "content", title: "Live: vom Bericht zum Dashboard", body: "Der dritte Teil wechselt zu **echten Daten**: den \u00f6ffentlichen **Wissensbilanzen** der Vetmeduni 2012 bis 2025 (vierzehn PDFs).\n\n\u2022 Referenzprojekt: PDFs, daraus gepr\u00fcfte Kennzahlen, daraus ein **Dashboard**\n\u2022 Methode **Promptotyping**: erst Wissen in Dokumente (*DATA.md*, *SPECIFICATION.md*), dann Code\n\u2022 \u00d6ffentliche Daten, daher ist ein *Cloud*-Agent wie *Claude Code* hier unbedenklich\n\nLive arbeiten wir mit der fertigen Kennzahlen-Datei; die fragile PDF-Extraktion ist vorbereitet.", source: "Wissensbilanzen der Veterin\u00e4rmedizinischen Universit\u00e4t Wien (vetmeduni.ac.at, Berichte) \u00b7 Repo: vetmed-datenanalyse", notes: "Der dritte Teil arbeitet mit echten oeffentlichen Daten. Universitaeten muessen ihre Wissensbilanz jaehrlich veroeffentlichen, die Kennzahlen folgen der Wissensbilanz-Verordnung. Das Referenzprojekt vetmed-datenanalyse extrahiert aus den vierzehn PDFs der Jahrgaenge 2012 bis 2025 die Personal- und Drittmittelkennzahlen und baut daraus ein Dashboard. Die Methode ist Promptotyping, also Wissen in Dokumenten vor Code. Weil alle Daten oeffentlich sind, ist der Einsatz eines Cloud-Agenten unbedenklich. Fuer interne oder personenbezogene Daten gilt das nicht, dort bleibt die Academic AI der Weg. Die PDF-Extraktion ist vorbereitet, weil sie auf echten Quellen fragil ist. Die Live-Demo arbeitet mit der fertigen Kennzahlen-Datei." },

    { type: "handson", title: "Der Arbeitsauftrag", body: "Worauf Sie live achten k\u00f6nnen:\n\n1. **Kontext zuerst**: das Modell liest *DATA.md*, bevor es rechnet\n2. **Permissions**: vor jeder Ausf\u00fchrung kommt die Nachfrage\n3. **Tests als Gate**: der **Datenvertrag** muss gr\u00fcn bleiben\n4. Ergebnis: das **Dashboard** im Browser", prompt: "Lies knowledge/DATA.md und\nknowledge/SPECIFICATION.md.\nArbeite mit den Kennzahlen in\ndata/kennzahlen/.\nPr\u00fcfe zuerst den Datenvertrag\n(python -m pytest -q).\nBaue dann das Dashboard neu und\nfasse die wichtigsten Befunde zu\nPersonal, Frauenanteil und\nDrittmitteln zusammen.", notes: "Der Auftrag wird live in Claude Code ausgefuehrt. Das Modell liest zuerst die Wissensdokumente DATA.md und SPECIFICATION.md, das ist der Kern von Promptotyping. Vor jeder Skript-Ausfuehrung kommt die Permission-Nachfrage. Der Datenvertrag in tests/test_datenvertrag.py prueft zwanzig Bedingungen, darunter Quersummen, Frauenanteile und verankerte Sollwerte aus den PDFs. Erst wenn die Tests gruen sind, wird das Dashboard gebaut und im Browser geoeffnet." },

    { type: "content_with_image", title: "Befund: Frauenanteil 2012 bis 2025", body: "\u2022 Wissenschaftliches Personal: Frauenanteil von **59 auf 66 %**\n\u2022 Professor:innen (ab 2021 berichtet): von **32 auf 53 %**, von 12 auf 25 Personen\n\u2022 Kleine Grundgesamtheit bei Professuren: einzelne Berufungen bewegen die Kurve stark\n\nLesehinweis: Die Werte sind **Kopfzahlen**, nicht *Vollzeit\u00e4quivalente*.", placeholder: "wb_frauenanteil.png\nFrauenanteil wiss. Personal und Professor:innen", source: "Wissensbilanzen Vetmeduni 2012\u20132025, Kennzahl 1.A.1; eigene Aufbereitung (vetmed-datenanalyse).", notes: "Die Abbildung zeigt den Frauenanteil nach Kopfzahl aus vierzehn Jahrgaengen. Im wissenschaftlichen Personal stieg der Anteil von 59,3 auf 66,4 Prozent. Bei den Professuren, die erst ab 2021 getrennt berichtet werden, stieg er von 31,6 auf 53,2 Prozent, in absoluten Zahlen von 12 auf 25 Professorinnen. Bei kleinen Grundgesamtheiten bewegen einzelne Berufungen die Kurve stark, das gehoert zur Interpretation dazu. Die Werte beziehen sich auf Kopfzahlen, nicht auf Vollzeitaequivalente." },

    { type: "content_with_image", title: "Befund: Personal und Drittmittel", body: "\u2022 Wissenschaftliches Personal: von 648 K\u00f6pfen (2012) zum H\u00f6chststand 2019, zuletzt 777\n\u2022 Drittmittelerl\u00f6se (F&E) schwanken deutlich: Spitze **21,7 Mio Euro** (2019), danach R\u00fcckgang und Erholung\n\u2022 Einzelne Gro\u00dfprojekte pr\u00e4gen die Jahressumme; die Schwankung selbst ist kein Alarmsignal", placeholder: "wb_personal_drittmittel.png\nPersonalstand und Drittmittelerl\u00f6se", source: "Wissensbilanzen Vetmeduni, Kennzahlen 1.A.1 und 1.C.1; eigene Aufbereitung (vetmed-datenanalyse).", notes: "Das wissenschaftliche Personal waechst von 648 Koepfen im Jahr 2012 auf einen Hoechststand um 2019 und liegt zuletzt bei 777. Das allgemeine Personal verlaeuft parallel auf niedrigerem Niveau. Die Drittmittelerloese aus Forschung und Entwicklung schwanken zwischen rund 10 und 21,7 Millionen Euro, das Spitzenjahr ist 2019. Einzelne Grossprojekte praegen die Jahressumme, deshalb ist die Schwankung selbst kein Alarmsignal. Beide Reihen stammen aus denselben oeffentlichen Berichten." },

    { type: "content_with_image", title: "Das Dashboard", body: "Eine einzige *HTML*-Datei, offline lauff\u00e4hig:\n\n\u2022 Kennzahlen-Karten mit Vorjahresvergleich\n\u2022 Diagramme zu Frauenanteil, Personalstand, Drittmitteln\n\u2022 Umschalter Kopfzahl/*VZ\u00c4*, Jahresfilter, *PNG*- und *CSV*-Export\n\nGebaut im Dialog mit *Claude Code*, gesichert durch den **Datenvertrag**.", placeholder: "wb_dashboard.png\nDashboard mit Kennzahlen-Karten und Frauenanteil", source: "vetmed-datenanalyse, dashboard/index.html.", notes: "Das Dashboard ist eine einzelne HTML-Datei ohne externe Abhaengigkeiten und laeuft offline per Doppelklick. Es zeigt Kennzahlen-Karten mit Vorjahresvergleich, Diagramme zu Frauenanteil, Personalstand und Drittmitteln, einen Umschalter zwischen Kopfzahl und Vollzeitaequivalenten, Jahresfilter sowie Export als PNG und CSV. Gebaut wurde es im Dialog mit Claude Code, die Datenbasis sichert der Datenvertrag mit zwanzig Pruefungen." },

    { type: "content", title: "Verifikation: der Datenvertrag", body: "Bei echten Daten pr\u00fcfen **Tests** statt bekannter Sollwerte:\n\n\u2022 **Konsistenz**: Frauen plus M\u00e4nner ergibt Gesamt, keine L\u00fccken, Frauenanteil korrekt berechnet\n\u2022 **Quellbindung**: verankerte Werte aus den PDFs (*Golden Values*), \u00dcberlappung benachbarter Jahrg\u00e4nge\n\nKonsistenz allein sichert keine Korrektheit gegen die Quelle. Die Anker setzt der Mensch: *Critical Expert in the Loop*.\n\n**Mehr Autonomie hei\u00dft mehr Verifikation, nicht weniger.** Vertiefung: *VetMed Winter School*.", notes: "Bei echten Daten gibt es keine vorab bekannten Sollwerte wie beim synthetischen Datensatz in Teil 2. An ihre Stelle tritt der Datenvertrag mit zwanzig Pruefungen auf zwei Ebenen. Die Konsistenzebene prueft, dass Frauen plus Maenner Gesamt ergibt, dass keine Jahrgaenge fehlen und dass der Frauenanteil korrekt berechnet ist. Die Quellbindungsebene verankert einzelne Werte direkt aus den PDFs und prueft die Ueberlappung benachbarter Jahrgaenge. Konsistenz allein sichert keine Korrektheit gegen die Quelle, erst beide Ebenen zusammen. Die verankerten Werte hat der Mensch aus den Quellen gesetzt. Je autonomer das Werkzeug arbeitet, desto wichtiger wird diese Pruefung. Die VetMed Winter School vertieft den Arbeitsmodus." }
  ];
}
