
// ============================================================
// WS5 Delta \u2014 Fable-5-Opener + Teil-3-Live-Demo (10.06.2026)
// Generiert aus build_content.py \u2014 nicht von Hand editieren.
// Fuer generateAppend(): haengt hinten an, danach manuell
// einsortieren (Opener nach Folie 1, Live-Demo nach Section Teil 3).
// ============================================================

function getWs5DeltaContent() {
  return [
    { type: "content", title: "Gestern erschienen: Claude Fable 5", body: "Anthropic ver\u00f6ffentlicht am 9. Juni 2026 **Claude Fable 5**, das erste \u00f6ffentliche Modell der **Mythos-Klasse**.\n\n\u2022 Eine eigene Leistungsstufe **\u00fcber** den bisherigen Spitzenmodellen\n\u2022 Stand der Technik auf nahezu allen *Benchmarks*\n\u2022 Arbeitet **l\u00e4nger autonom** an komplexen Aufgaben als jedes fr\u00fchere Modell\n\n**Die Entwicklung flacht nicht ab.** Was das f\u00fcr die t\u00e4gliche Arbeit mit Daten hei\u00dft, ist Thema dieses Workshops.", source: "Anthropic (2026). Claude Fable 5 and Claude Mythos 5. anthropic.com/news.", notes: "Anthropic hat am 9. Juni 2026 Claude Fable 5 veroeffentlicht, das erste oeffentlich zugaengliche Modell der Mythos-Klasse. Es liegt als eigene Leistungsstufe ueber den bisherigen Opus-Spitzenmodellen, ist Stand der Technik auf nahezu allen Benchmarks und arbeitet laenger autonom an komplexen Aufgaben als jedes fruehere Claude-Modell. Die Entwicklung seit 2023 setzt sich damit ungebremst fort." },

    { type: "content", title: "Mythos und Fable: Sicherheit als Systemdesign", body: "Das volle Modell **Mythos 5** erh\u00e4lt nur ein kleiner Kreis von Cyberverteidigern und Infrastrukturbetreibern (*Project Glasswing*, mit der US-Regierung).\n\nDas \u00f6ffentliche **Fable 5** hat eingebaute **Klassifikatoren**: Anfragen zu *Cybersecurity*, Bio/Chemie oder Modell-*Destillation* beantwortet automatisch ein schw\u00e4cheres Modell.\n\n**Verantwortung wird ins System gebaut.** Dieselbe Logik begleitet uns heute auf Nutzerseite: pr\u00fcfen, bevor man vertraut.\n\nDie Live-Demo am Ende l\u00e4uft auf genau diesem Modell.", source: "Anthropic (2026). Claude Fable 5 and Claude Mythos 5. anthropic.com/news.", notes: "Das volle Modell Mythos 5 erhaelt nur ein kleiner Kreis von Cyberverteidigern und Infrastrukturbetreibern im Rahmen von Project Glasswing in Kooperation mit der US-Regierung, weil die Mythos-Modelle Schwachstellen auf uebermenschlichem Niveau finden. Das oeffentliche Fable 5 nutzt dieselbe Technologie, aber Klassifikatoren leiten Anfragen zu Cybersecurity, Biologie und Chemie oder Modell-Destillation automatisch an ein schwaecheres Modell um. Die Verantwortung liegt damit nicht allein beim Nutzer, sondern ist in das System eingebaut. Die Live-Demo in Teil 3 laeuft auf Fable 5." },

    { type: "content", title: "Live: derselbe Fall in *Claude Code*", body: "Gleiche Daten, gleiche Fragen wie eben. Ein Unterschied:\n\n\u2022 Teil 2: **f\u00fcnf Fragen** nacheinander, nach jeder gepr\u00fcft\n\u2022 Jetzt: **ein Arbeitsauftrag**, formuliert wie an eine Kollegin\n\nDas Werkzeug plant die Schritte selbst, schreibt den Code und f\u00fchrt ihn aus. Am Ende steht ein **HTML-Report**, der beim n\u00e4chsten Quartal mit neuen Daten erneut laufen kann.", notes: "Der dritte Teil zeigt denselben Verwaltungsfall in Claude Code. In Teil 2 wurden fuenf Fragen nacheinander gestellt und nach jeder geprueft. Jetzt wird der gesamte Arbeitsauftrag auf einmal formuliert, so wie man ihn einer Kollegin geben wuerde. Das Werkzeug plant die Schritte selbst, schreibt ein Python-Skript und erzeugt einen HTML-Report, der beim naechsten Quartal mit neuen Daten erneut laufen kann." },

    { type: "handson", title: "Der eine Auftrag", body: "Worauf Sie live achten k\u00f6nnen:\n\n1. **Planung**: das Modell legt sich einen Arbeitsplan an\n2. **Permissions**: vor der Skript-Ausf\u00fchrung kommt die Nachfrage\n3. **Code statt Sch\u00e4tzen**: es schreibt und pr\u00fcft *Python*\n4. Findet es die **Schreibvarianten-Falle** selbst?", prompt: "Lies VetMed_Verwaltung_Demodaten.xlsx\n(Blatt \"Personal\") und erstelle die\nPersonalauswertung f\u00fcr die\nWissensbilanz: Kopfzahl und VZ\u00c4 je\nOrganisationseinheit, Geschlechter-\nverteilung gesamt und je Funktions-\ngruppe. Pr\u00fcfe und bereinige die\nDatenqualit\u00e4t, dokumentiere jede\nBereinigung. Erzeuge einen HTML-\nReport mit Tabellen und Diagrammen.\nVerifiziere die Quersummen gegen\ndie Zeilenzahl.", notes: "Der Auftrag steht zum Mitlesen auf der Folie und wird live in Claude Code ausgefuehrt. Sichtbar werden der Arbeitsplan des Modells, die Permission-Nachfrage vor der Skript-Ausfuehrung und die Code-Ausfuehrung selbst. Offen bleibt, ob das Modell die zwei Schreibweisen der Kleintierklinik ohne Hinweis zusammenfuehrt. Falls nicht, erfolgt der Eingriff live." },

    { type: "content", title: "Verifikation: Sie kennen die Zahlen", body: "Die Sollwerte aus Teil 2 sind der Pr\u00fcfanker:\n\n\u2022 **150** Personen, **110,00** VZ\u00c4\n\u2022 Kleintierklinik **20** (nicht 12 + 8)\n\u2022 Frauenanteil **46 %**\n\n\u00dcbersieht das Modell die Schreibvarianten, greifen wir ein. Genau das ist die Rolle des *Critical Expert*.\n\n**Mehr Autonomie hei\u00dft mehr Verifikation, nicht weniger.** Vertiefung: *VetMed Winter School*.", notes: "Die Teilnehmenden kennen die Sollwerte aus Teil 2 und pruefen das Ergebnis selbst. 150 Personen, 110 Vollzeitaequivalente, 20 Personen in der konsolidierten Kleintierklinik und 46 Prozent Frauenanteil. Uebersieht das Modell die Schreibvarianten, wird live eingegriffen. Die Verifikations-Checkliste gilt fuer beide Werkzeuge unveraendert. Je autonomer das Werkzeug arbeitet, desto wichtiger wird die Pruefung. Die VetMed Winter School vertieft diesen Arbeitsmodus." }
  ];
}
